version: '3.8'

services:
  django_app:
    image: mubarakbunza/django_app:${ENV}
    ports:
      - "${PORT}:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=${DB_URL}
    volumes:
      - ./static:/app/static
