version: '3.8'

services:
  django_app:
    image: mubarakbunza/django_app:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DATABASE_URL=postgres://django_user:secure_password@localhost:5432/django_db
    volumes:
      - ./static:/app/static
