name: Staging Deloyment

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t django_app:staging .

    - name: Push Docker image to registry
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker tag django_app:staging "$DOCKER_USER"/django_app:staging
        docker push "$DOCKER_USER"/django_app:staging

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy Using SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.STG_SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.STG_SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo docker pull ${{ secrets.DOCKER_USER }}/django_app:staging
          sudo docker service update --image ${{ secrets.DOCKER_USER }}/django_app:staging afripoints_django_app
